/**
 * 知识星盘 —— 节点数据（参考层的灵魂导航）
 *
 * 设计要点（中文优先原则）：
 * 1. name 一律为中文，节点上只显示中文
 * 2. en 为英文拼写，只在悬停 Tooltip 与「光之翼」详情面板中出现
 * 3. tags 收录中文口语化说法（如「横着排」「排均匀」），供搜索框联想定位
 * 4. x / y 为相对坐标（0-100），组件内换算为像素位置
 */

export type ConstellationId = "morning" | "cloud" | "rain" | "dusk";

export interface Constellation {
  id: ConstellationId;
  name: string; // 星座中文名
  en: string; // 对应技术域
  color: string; // 主色
  glow: string; // 光晕色（rgba）
  icon: string;
  description: string;
}

export interface StarNode {
  id: string;
  name: string; // 中文显示名
  en: string; // 英文拼写（Tooltip / 详情面板）
  level: 1 | 2 | 3; // 1 大星星（核心模块） 2 中星星（关键概念） 3 小星星（具体属性/坑点）
  constellation: ConstellationId;
  x: number; // 相对位置 0-100
  y: number;
  desc: string; // 中文解释（一句话）
  phonetic?: string; // 音节拆分（e.g. "just-i-fy"）
  mnemonic?: string; // 中文谐音助记
  code?: string; // 代码示例
  tags: string[]; // 中文口语化标签（搜索用）
  links?: string[]; // 星轨连接关系（流向的子节点 id）
  /** 星芒射线数量（仅大/中星星生效，缺省按层级默认：大 12 / 中 8） */
  rayCount?: number;
  /** 光晕强度倍率（0-1，缺省按层级默认：大 1 / 中 0.65 / 小 0.4） */
  glowIntensity?: number;
}

/** 四大星座分区 */
export const constellations: Constellation[] = [
  {
    id: "morning",
    name: "晨岛",
    en: "HTML",
    color: "#6ea8ff",
    glow: "rgba(110,168,255,0.85)",
    icon: "🟦",
    description: "HTML 的起点，语义化是照亮旅程的第一颗星",
  },
  {
    id: "cloud",
    name: "云野",
    en: "CSS",
    color: "#34d399",
    glow: "rgba(52,211,153,0.85)",
    icon: "🟩",
    description: "CSS 的世界，弹性布局是贯穿云海的主星轨",
  },
  {
    id: "rain",
    name: "雨林",
    en: "JavaScript",
    color: "#fbbf24",
    glow: "rgba(251,191,36,0.85)",
    icon: "🟨",
    description: "JavaScript 的雨幕，核心语言是电闪雷鸣的中心",
  },
  {
    id: "dusk",
    name: "暮土",
    en: "工程化",
    color: "#a78bfa",
    glow: "rgba(167,139,250,0.85)",
    icon: "⬛",
    description: "工程化的暗夜，Git 是守护版本历史的黑武士",
  },
];

/** 星盘节点（坐标已按四象限排布，避免重叠） */
export const stars: StarNode[] = [
  // ==================== 🟦 晨岛 · HTML（左上） ====================
  {
    id: "semantic",
    name: "语义化",
    en: "semantic",
    level: 1,
    rayCount: 12,
    glowIntensity: 1,
    constellation: "morning",
    x: 21,
    y: 16,
    desc: "用有含义的标签（header/nav/article…）描述内容结构，机器和人一看就懂",
    phonetic: "se-man-tic",
    mnemonic: "赛曼提克 —— 有「语义」才赛高",
    code: "<header>页头</header>\n<nav>导航</nav>\n<article>正文</article>\n<footer>页脚</footer>",
    tags: ["语义化", "结构", "标签", "骨架", "意思清楚"],
    links: ["structure", "form", "media", "seo", "meta", "title", "alt"],
  },
  {
    id: "structure",
    name: "文档结构",
    en: "document structure",
    level: 2,
    constellation: "morning",
    x: 9,
    y: 32,
    desc: "html/head/body 三层的标准骨架，是一切页面的地基",
    phonetic: "doc-u-ment",
    mnemonic: "道库门特 —— 文档即「道」",
    tags: ["骨架", "文档", "结构", "头部", "头部信息"],
    links: ["title"],
  },
  {
    id: "form",
    name: "表单验证",
    en: "form validation",
    level: 2,
    constellation: "morning",
    x: 33,
    y: 30,
    desc: "收集用户输入并做校验：必填、格式、长度，前端拦一道，后端再拦一道",
    tags: ["表单", "输入", "提交", "校验", "必填"],
    links: ["placeholder", "required", "input-type"],
  },
  {
    id: "media",
    name: "多媒体",
    en: "media",
    level: 2,
    constellation: "morning",
    x: 9,
    y: 46,
    desc: "图片、视频、音频、内嵌页面的插入与适配",
    phonetic: "me-di-a",
    mnemonic: "米迪亚 —— 媒体是「米」",
    tags: ["图片", "视频", "音频", "播放", "嵌入"],
    links: ["alt", "video-audio", "iframe"],
  },
  {
    id: "seo",
    name: "SEO 优化",
    en: "search engine optimization",
    level: 2,
    constellation: "morning",
    x: 30,
    y: 46,
    desc: "让搜索引擎读懂你的页面：meta 描述、标题、结构化数据",
    phonetic: "e-se-o",
    mnemonic: "E-SEO —— 搜索的「SEO」",
    tags: ["搜索", "排名", "优化", "描述", "收录"],
    links: ["meta"],
  },
  {
    id: "placeholder",
    name: "占位提示",
    en: "placeholder",
    level: 3,
    constellation: "morning",
    x: 44,
    y: 22,
    desc: "输入框里的灰色示例文字，聚焦即消失",
    phonetic: "place-holder",
    mnemonic: "普雷斯·霍尔德 —— 占「位」的持有者",
    code: '<input placeholder="请输入用户名" />',
    tags: ["占位", "灰色字", "提示文字", "示例"],
  },
  {
    id: "required",
    name: "必填",
    en: "required",
    level: 3,
    constellation: "morning",
    x: 42,
    y: 38,
    desc: "标记输入项必须填写，不填无法提交",
    phonetic: "re-qui-red",
    mnemonic: "瑞奎尔德 —— 被「需要」的",
    code: '<input type="text" required />',
    tags: ["必填", "不能不填", "校验", "不能为空"],
  },
  {
    id: "input-type",
    name: "输入类型",
    en: "input type",
    level: 3,
    constellation: "morning",
    x: 30,
    y: 27,
    desc: "input 的 type 决定输入形态：text/password/email/number…",
    code: '<input type="email" />\n<input type="password" />',
    tags: ["输入框", "类型", "密码", "邮箱", "数字", "手机号"],
  },

  {
    id: "meta",
    name: "页面描述",
    en: "meta description",
    level: 3,
    constellation: "morning",
    x: 40,
    y: 54,
    desc: "head 里的 meta 标签：描述、关键词、字符集，是页面的名片",
    code: '<meta charset="UTF-8" />\n<meta name="description" content="一句话介绍" />',
    tags: ["描述", "简介", "编码", "字符集", "关键词"],
  },
  {
    id: "title",
    name: "页面标题",
    en: "title",
    level: 3,
    constellation: "morning",
    x: 2,
    y: 24,
    desc: "浏览器页签上显示的文字，也是 SEO 的重要一环",
    code: "<title>我的页面</title>",
    tags: ["标题", "页签", "名字"],
  },
  {
    id: "alt",
    name: "图片说明",
    en: "alt attribute",
    level: 3,
    constellation: "morning",
    x: 18,
    y: 58,
    desc: "图片无法显示时展示的文字，读屏软件也靠它朗读",
    code: '<img src="cat.png" alt="一只橘猫" />',
    tags: ["图片", "说明", "图挂了", "替代文字", "无障碍"],
  },
  {
    id: "video-audio",
    name: "影音播放",
    en: "video / audio",
    level: 3,
    constellation: "morning",
    x: 4,
    y: 58,
    desc: "原生音视频标签，自带控制条与事件",
    code: '<video src="movie.mp4" controls></video>\n<audio src="bgm.mp3" controls></audio>',
    tags: ["视频", "音频", "播放", "控制条", "音乐"],
  },
  {
    id: "iframe",
    name: "内嵌网页",
    en: "iframe",
    level: 3,
    constellation: "morning",
    x: 32,
    y: 58,
    desc: "在一个页面里嵌入另一个页面（地图/视频/第三方表单）",
    phonetic: "i-frame",
    mnemonic: "爱·弗雷姆 —— 内嵌的「框」",
    code: '<iframe src="https://example.com"></iframe>',
    tags: ["内嵌", "嵌入", "地图", "第三方"],
  },

  // ==================== 🟩 云野 · CSS（右上） ====================
  {
    id: "flex",
    name: "弹性布局",
    en: "flexbox",
    level: 1,
    rayCount: 12,
    glowIntensity: 1,
    constellation: "cloud",
    x: 78,
    y: 16,
    desc: "一维布局首选：容器一行声明，项目自动排列、自动对齐、自动伸缩",
    phonetic: "flex-box",
    mnemonic: "弗莱克斯盒子 —— 会伸缩的盒子",
    code: ".parent {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}",
    tags: ["横着排", "竖着放", "弹性", "对齐", "居中", "排均匀", "平分"],
    links: ["box-model", "grid", "position", "animation", "align-items", "gap", "flex-basis"],
  },
  {
    id: "box-model",
    name: "盒模型",
    en: "box model",
    level: 2,
    constellation: "cloud",
    x: 66,
    y: 32,
    desc: "每个元素都是一个盒子：内容 + 内边距 + 边框 + 外边距",
    phonetic: "box mod-el",
    mnemonic: "盒子模特 —— 有棱有角",
    code: "* { box-sizing: border-box; }",
    tags: ["盒子", "内边距", "边框", "外边距", "尺寸", "宽度"],
    links: ["margin-collapse"],
  },
  {
    id: "grid",
    name: "网格布局",
    en: "grid",
    level: 2,
    constellation: "cloud",
    x: 90,
    y: 30,
    desc: "二维布局：同时控制行和列，适合宫格、卡片墙",
    phonetic: "grid",
    mnemonic: "格瑞德 —— 网格的「格」",
    code: ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 12px;\n}",
    tags: ["九宫格", "宫格", "二维", "行列", "卡片墙"],
  },
  {
    id: "position",
    name: "定位",
    en: "position",
    level: 2,
    constellation: "cloud",
    x: 64,
    y: 48,
    desc: "把元素从文档流里拎出来，按参照物摆放：fixed/absolute/sticky",
    phonetic: "po-si-tion",
    mnemonic: "波西审 —— 摆放「位置」",
    code: ".top { position: sticky; top: 0; }",
    tags: ["定位", "悬浮", "吸顶", "固定", "参照物"],
    links: ["z-index"],
  },
  {
    id: "animation",
    name: "动画",
    en: "animation",
    level: 2,
    constellation: "cloud",
    x: 90,
    y: 48,
    desc: "关键帧驱动的自动动画：旋转、呼吸、循环、入场",
    tags: ["动画", "关键帧", "旋转", "呼吸", "循环"],
    links: ["keyframes", "transform"],
  },
  {
    id: "align-items",
    name: "垂直对齐",
    en: "align-items",
    level: 3,
    constellation: "cloud",
    x: 70,
    y: 6,
    desc: "flex/grid 容器里，控制项目在交叉轴（默认竖轴）上的对齐",
    code: ".parent { display: flex; align-items: center; }",
    tags: ["垂直对齐", "上下居中", "对齐"],
  },
  {
    id: "gap",
    name: "间距",
    en: "gap",
    level: 3,
    constellation: "cloud",
    x: 88,
    y: 6,
    desc: "flex/grid 项目之间的统一间距，替代古老的 margin 方案",
    code: ".parent { display: flex; gap: 16px; }",
    tags: ["间距", "缝隙", "空隙", "隔开"],
  },
  {
    id: "flex-basis",
    name: "基础尺寸",
    en: "flex-basis",
    level: 3,
    constellation: "cloud",
    x: 58,
    y: 22,
    desc: "弹性项目伸缩前的初始尺寸，flex 三兄弟之一",
    code: ".item { flex: 1 1 200px; }",
    tags: ["基础尺寸", "宽度", "弹性基准", "初始大小"],
  },
  {
    id: "margin-collapse",
    name: "外边距合并",
    en: "margin collapse",
    level: 3,
    constellation: "cloud",
    x: 58,
    y: 40,
    desc: "垂直方向相邻的 margin 会合并取大值，新手必踩的坑",
    tags: ["外边距", "合并", "塌陷", "取大值"],
  },
  {
    id: "z-index",
    name: "层叠顺序",
    en: "z-index",
    level: 3,
    constellation: "cloud",
    x: 56,
    y: 58,
    desc: "控制定位元素谁压谁，数字越大越靠上",
    code: ".modal { position: fixed; z-index: 100; }",
    tags: ["层叠", "压住", "盖住", "谁在上面", "遮挡"],
  },
  {
    id: "keyframes",
    name: "关键帧",
    en: "@keyframes",
    level: 3,
    constellation: "cloud",
    x: 86,
    y: 60,
    desc: "定义动画各阶段的状态，配合 animation 使用",
    code: "@keyframes spin {\n  to { transform: rotate(360deg); }\n}",
    tags: ["关键帧", "循环", "动画帧", "旋转动画"],
  },
  {
    id: "transform",
    name: "变换",
    en: "transform",
    level: 3,
    constellation: "cloud",
    x: 72,
    y: 60,
    desc: "对元素做旋转/缩放/平移/倾斜，GPU 加速不重排",
    code: ".box:hover { transform: scale(1.1); }",
    tags: ["旋转", "缩放", "平移", "倾斜", "放大"],
  },

  // ==================== 🟨 雨林 · JavaScript（左下） ====================
  {
    id: "js-core",
    name: "JS 核心",
    en: "JavaScript",
    level: 1,
    rayCount: 12,
    glowIntensity: 1,
    constellation: "rain",
    x: 21,
    y: 80,
    desc: "一切前端交互的引擎：变量、函数、对象、异步都从这里长出来",
    tags: ["javascript", "脚本", "核心", "基础", "语言"],
    links: [
      "closure",
      "prototype",
      "promise",
      "event-loop",
      "this-binding",
      "let-const",
      "arrow-fn",
      "map-reduce",
      "async-await",
      "event-delegation",
    ],
  },
  {
    id: "closure",
    name: "闭包",
    en: "closure",
    level: 2,
    constellation: "rain",
    x: 8,
    y: 66,
    desc: "函数记住了它诞生时的作用域，即使外层已返回也能访问那些变量",
    phonetic: "clo-sure",
    mnemonic: "克楼热 —— 把变量「关」起来",
    code: "function counter() {\n  let n = 0;\n  return () => ++n;\n}",
    tags: ["闭包", "记住变量", "私有", "作用域", "计数器"],
  },
  {
    id: "prototype",
    name: "原型链",
    en: "prototype chain",
    level: 2,
    constellation: "rain",
    x: 34,
    y: 66,
    desc: "对象找属性找不到时，沿着 __proto__ 一路向上找，直到 null",
    code: "Array.prototype.myMethod = function () {}",
    tags: ["原型", "继承", "挂方法", "原型链", "__proto__"],
  },
  {
    id: "promise",
    name: "Promise",
    en: "Promise",
    level: 2,
    constellation: "rain",
    x: 8,
    y: 92,
    desc: "异步结果的「承诺」对象：pending → fulfilled / rejected，可链式调用",
    phonetic: "pro-mise",
    mnemonic: "普拉米斯 —— 向你「许诺」",
    code: "fetch(url)\n  .then((r) => r.json())\n  .catch((e) => console.error(e));",
    tags: ["承诺", "异步", "回调", "链式", "then", "回调地狱"],
  },
  {
    id: "event-loop",
    name: "事件循环",
    en: "event loop",
    level: 2,
    constellation: "rain",
    x: 32,
    y: 94,
    desc: "JS 单线程的调度中枢：同步先跑，微任务先于宏任务",
    tags: ["事件循环", "微任务", "宏任务", "顺序", "单线程"],
  },
  {
    id: "this-binding",
    name: "this 指向",
    en: "this",
    level: 3,
    constellation: "rain",
    x: 16,
    y: 74,
    desc: "this 指「谁调用它」，而不是「谁定义它」；箭头函数没有自己的 this",
    code: "btn.onclick = () => console.log(this); // 箭头函数 = 外层 this",
    tags: ["this", "指向", "调用者", "箭头函数"],
  },
  {
    id: "let-const",
    name: "块级变量",
    en: "let / const",
    level: 3,
    constellation: "rain",
    x: 28,
    y: 72,
    desc: "ES6 块级作用域声明：let 可改、const 只读，告别 var 的坑",
    code: "let count = 0;\nconst MAX = 10;",
    tags: ["变量", "声明", "块级", "常量", "const"],
  },
  {
    id: "arrow-fn",
    name: "箭头函数",
    en: "arrow function",
    level: 3,
    constellation: "rain",
    x: 40,
    y: 76,
    desc: "函数的简写形式，且不绑定自己的 this",
    code: "const add = (a, b) => a + b;",
    tags: ["箭头", "简写", "函数", "=>"],
  },
  {
    id: "map-reduce",
    name: "数组三兄弟",
    en: "map / filter / reduce",
    level: 3,
    constellation: "rain",
    x: 14,
    y: 84,
    desc: "声明式遍历：map 加工、filter 过滤、reduce 累加，不污染原数组",
    code: "arr.map(x => x * 2)\n   .filter(x => x > 10)\n   .reduce((a, b) => a + b, 0)",
    tags: ["遍历", "加工", "累加", "过滤", "reduce"],
  },
  {
    id: "async-await",
    name: "异步等待",
    en: "async / await",
    level: 3,
    constellation: "rain",
    x: 30,
    y: 86,
    desc: "让异步代码长得像同步：await 会「暂停」函数直到 Promise 落定",
    code: "async function load() {\n  const data = await fetch(url);\n  return data.json();\n}",
    tags: ["等待", "暂停", "同步写法", "异步"],
  },
  {
    id: "event-delegation",
    name: "事件委托",
    en: "event delegation",
    level: 3,
    constellation: "rain",
    x: 40,
    y: 88,
    desc: "把事件绑到父元素，靠冒泡捕获子元素触发，动态列表的救星",
    code: "list.onclick = (e) => {\n  if (e.target.closest('button')) { /* … */ }\n}",
    tags: ["事件委托", "冒泡", "代理", "动态列表"],
  },

  // ==================== ⬛ 暮土 · 工程化（右下） ====================
  {
    id: "git",
    name: "版本控制",
    en: "Git",
    level: 1,
    rayCount: 12,
    glowIntensity: 1,
    constellation: "dusk",
    x: 79,
    y: 80,
    desc: "记录每次修改的快照，随时回退、多线并行、多人协作的基石",
    tags: ["版本控制", "回退", "快照", "提交", "历史"],
    links: ["npm", "build", "lint", "commit", "branch", "merge", "rebase", "gitignore"],
  },
  {
    id: "npm",
    name: "包管理",
    en: "npm",
    level: 2,
    constellation: "dusk",
    x: 66,
    y: 66,
    desc: "Node 的包管理器：装依赖、跑脚本、发布包",
    phonetic: "n-p-m",
    mnemonic: "「嗯怕米」—— node 包管理器",
    code: "npm install lodash\nnpm run build",
    tags: ["包", "依赖", "安装", "脚手架", "npm"],
    links: ["package-json", "node-modules"],
  },
  {
    id: "build",
    name: "构建工具",
    en: "build tool",
    level: 2,
    constellation: "dusk",
    x: 92,
    y: 66,
    desc: "把源码打包成浏览器能用的产物：压缩、转译、拆包",
    tags: ["构建", "打包", "编译", "压缩", "vite"],
  },
  {
    id: "lint",
    name: "代码规范",
    en: "ESLint / Prettier",
    level: 2,
    constellation: "dusk",
    x: 79,
    y: 93,
    desc: "用工具统一代码风格、拦截低级错误，团队协作的「宪法」",
    tags: ["规范", "检查", "报错", "格式", "eslint"],
  },
  {
    id: "commit",
    name: "提交",
    en: "commit",
    level: 3,
    constellation: "dusk",
    x: 62,
    y: 74,
    desc: "把一组改动存成一次快照，附上说明文字",
    code: 'git add .\ngit commit -m "feat: 新增登录页"',
    tags: ["提交", "保存", "快照", "记录"],
  },
  {
    id: "branch",
    name: "分支",
    en: "branch",
    level: 3,
    constellation: "dusk",
    x: 72,
    y: 72,
    desc: "从主线分出独立开发线，互不干扰，完事后合并回去",
    code: "git checkout -b feature/login",
    tags: ["分支", "新线", "隔离", "feature"],
  },
  {
    id: "merge",
    name: "合并",
    en: "merge",
    level: 3,
    constellation: "dusk",
    x: 88,
    y: 74,
    desc: "把一条分支的改动并回另一条分支",
    code: "git merge feature/login",
    tags: ["合并", "融合", "并回"],
  },
  {
    id: "rebase",
    name: "变基",
    en: "rebase",
    level: 3,
    constellation: "dusk",
    x: 94,
    y: 86,
    desc: "把当前分支的提交「重放」到另一条基线上，历史更线性",
    code: "git rebase main",
    tags: ["变基", "重排", "历史", "线性"],
  },
  {
    id: "package-json",
    name: "项目清单",
    en: "package.json",
    level: 3,
    constellation: "dusk",
    x: 60,
    y: 84,
    desc: "项目的身份证：依赖列表、脚本命令、版本号都在这",
    tags: ["项目", "清单", "依赖列表", "scripts"],
  },
  {
    id: "node-modules",
    name: "依赖目录",
    en: "node_modules",
    level: 3,
    constellation: "dusk",
    x: 70,
    y: 90,
    desc: "npm 安装的第三方代码存放处，体积巨大且可随时重建",
    tags: ["依赖", "目录", "很大", "不用提交", "node_modules"],
  },
  {
    id: "gitignore",
    name: "忽略规则",
    en: ".gitignore",
    level: 3,
    constellation: "dusk",
    x: 88,
    y: 92,
    desc: "告诉 Git 哪些文件不要跟踪：node_modules、日志、构建产物",
    code: "node_modules/\n*.log\ndist/",
    tags: ["忽略", "排除", "不上传", "gitignore"],
  },
];

/** 按 id 索引节点 */
export const starMap: Record<string, StarNode> = Object.fromEntries(stars.map((s) => [s.id, s]));
